# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: feature/feature_api.proto for package 'ProtoSum.Feature.FeatureApiPb'

require 'grpc'
require 'feature/feature_api_pb'

module ProtoSum
  module Feature
    module FeatureApiPb
      module FeatureService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'feature.feature_api_pb.FeatureService'

          rpc :GetFeature, ::ProtoSum::Feature::FeatureApiPb::Point, ::ProtoSum::Feature::FeatureApiPb::Feature
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
