# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/post.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "postpb.Post" do
    optional :name, :string, 1
    optional :type, :int64, 2
    optional :user_name, :int64, 3
  end
end

module Proto::PostPb
  Post = Google::Protobuf::DescriptorPool.generated_pool.lookup("postpb.Post").msgclass
end
