# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/user.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "userpb.User" do
    optional :name, :string, 1
    optional :age, :int64, 2
  end
end

module Proto::UserPb
  User = Google::Protobuf::DescriptorPool.generated_pool.lookup("userpb.User").msgclass
end
